version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
       - wordpress_test_network
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: soluto/knowledgebase-tests:latest
     ports:
       - "8000:80"
     volumes:
       - ../wordpress-docker-data:/var/www/html
       - ../knowledgebase-plugins:/var/www/html/wp-content/plugins:ro
       - ../knowledgebase-wordpress-theme:/var/www/html/wp-content/themes/empty-theme:ro
     restart: always
     networks:
       - wordpress_test_network
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
networks:
  wordpress_test_network:
volumes:
    db_data: