version: '3'

services:
   wordpress:
     volumes:
       - ../wordpress-docker-data:/var/www/html
       - ../knowledgebase-plugins:/var/www/html/wp-content/plugins
       - ../knowledgebase-wordpress-theme:/var/www/html/wp-content/themes/empty-theme